USE SoftwareShop;
ALTER TABLE Games WITH CHECK
ADD CONSTRAINT FK_PlatformID FOREIGN KEY (PlatformID) REFERENCES Platforms(PlatformID)
ON UPDATE CASCADE
GO

ALTER TABLE Games WITH CHECK
ADD CONSTRAINT FK_RatingID FOREIGN KEY (RatingID) REFERENCES Ratings(RatingID)
ON UPDATE CASCADE
GO

ALTER TABLE Memberships WITH CHECK
ADD CONSTRAINT FK_DiscountID FOREIGN KEY (DiscountID) REFERENCES Discounts(DiscountID)
ON UPDATE CASCADE
GO

ALTER TABLE ReceiptDetails WITH CHECK
ADD CONSTRAINT FK_GameID FOREIGN KEY (GameID) REFERENCES Games(GameID)
ON UPDATE CASCADE
GO

ALTER TABLE ReceiptDetails
ADD CONSTRAINT FK_DiscountID2 FOREIGN KEY(DiscountID) REFERENCES Discounts(DiscountID)
GO

ALTER TABLE ReceiptDetails WITH CHECK
ADD CONSTRAINT FK_Connection FOREIGN KEY(ReceiptID) REFERENCES Receipts(ReceiptID)
ON UPDATE CASCADE
GO